### ISSUE TITLE
Docs not loading

### ISSUE THREAD

**Issue by TomAugspurger** [fsspec/kerchunk#157]
Currently https://fsspec.github.io/kerchunk/ is erroring. IIUC https://github.com/fsspec/kerchunk/actions/runs/2272091237 is the GitHub Action that deployed the site, and it's all green.

Anyone more familiar with how the docs are built know what's up?

**Comment by lsterzinger** [comment]
The action was failing earlier today because numpydoc had updated to require Sphinx 3.0, but the action's image contained an earlier sphinx version. I pinned numpydoc at an older version in #155 and that's what got the test green again... not too sure what could have happened here

**Comment by lsterzinger** [comment]
Reran the build and deploy action again and it has failed... https://github.com/fsspec/kerchunk/actions/runs/2272091237

It kind of looks like there's something on GitHub's side that's not working?
```
Actor: lsterzinger
Action ID: 2272091237
Artifact URL: https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/pipelines/workflows/2272091237/artifacts?api-version=6.0-preview
{"count":1,"value":[{"containerId":13586339,"size":14243840,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/resources/Containers/13586339","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/pipelines/1/runs/447/artifacts?artifactName=github-pages","expiresOn":"2022-08-02T21:52:54.6742992Z","items":null}]}
Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/pipelines/1/runs/447/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "834afb5a9f109e87b585bee236c2e2c34834aa7f",
	"oidc_token": "***"
}
Failed to create deployment for 834afb5a9f109e87b585bee236c2e2c34834aa7f.
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 404
Error: Error: Request failed with status code 404
```

**Comment by lsterzinger** [comment]
https://fsspec.github.io is also not working, so I think it's a larger issue with that Github Pages site. @martindurant do you know where that's hosted? I thought that with how github pages worked there should be a fsspec.github.io repo but I don't see one anywhere

**Comment by lsterzinger** [comment]
Okay so it doesn't seem to be an issue with the build action that I touched earlier. Docs are building fine and the `gh-pages` branch seems to be normal (checking it out locally I'm able to browse the docs as normal). It seems like the problem is during the push of the `gh-pages` branch to the Github Pages system... but I'm not familiar enough with this to know what to do to troubleshoot this

**Comment by martindurant** [comment]
fsspec is on RTD, so that's not informative. Site is still down - can the deploy action be updated?

**Comment by lsterzinger** [comment]
It doesn't seem like it, it's activated when you turn on github pages for the repo. It doesn't seem to be related to any action yaml file

**Comment by TomAugspurger** [comment]
It seems that the build reported as failed now. I think it was passing earlier.

<img width="927" alt="Screen Shot 2022-05-07 at 7 12 19 AM" src="https://user-images.githubusercontent.com/1312546/167253902-e5e4d232-0bbe-4527-a57f-2326a61f9871.png">

I started a new build in https://github.com/fsspec/kerchunk/actions/runs/2272091237. It failed, but at least there are some logs now.

**Comment by lsterzinger** [comment]
The offending section is not very informative

```
Run actions/deploy-pages@v1
Actor: TomAugspurger
Action ID: 2272091237
Artifact URL: https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/pipelines/workflows/2272091237/artifacts?api-version=6.0-preview
{"count":1,"value":[{"containerId":13682535,"size":14243840,"signedContent":null,"fileContainerResourceUrl":"https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/resources/Containers/13682535","type":"actions_storage","name":"github-pages","url":"https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/pipelines/1/runs/457/artifacts?artifactName=github-pages","expiresOn":"2022-08-05T12:13:37.8562147Z","items":null}]}
Creating deployment with payload:
{
	"artifact_url": "https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/pipelines/1/runs/457/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "834afb5a9f109e87b585bee236c2e2c34834aa7f",
	"oidc_token": "***"
}
Failed to create deployment for 834afb5a9f109e87b585bee236c2e2c34834aa7f.
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-github-pages-deployment"}
Error: Error: Request failed with status code 404
Error: Error: Request failed with status code 404
```

**Comment by keewis** [comment]
if I read this correctly, it can't find the built artifact:
```
https://pipelines.actions.githubusercontent.com/ZlpFfYpg9zvsOGf2rz1wyStGj6aJt50AkF46egoIzqRfvDDIoV/_apis/pipelines/1/runs/457/artifacts?artifactName=github-pages&%24expand=SignedContent
```
returns a 404

Not sure how to fix that, though, especially since that requires authentication to verify. Maybe try if deleting the latest (failing) commit in `gh-pages` and then rerunning the `docs` action helps?

**Comment by valeriupredoi** [comment]
@keewis we've seen that issue just about every two weeks or so, it's GitHub-related, could you maybe try and trigger the pages build again, hopefully all goes well, could really use the docs now, I'm trying to learn the ins and outs of kerchunks :grin:

**Comment by lsterzinger** [comment]
@valeriupredoi I tried re-running the job and still the same error. When you run into this same issue, there's nothing to be done except just wait? Does it usually take this long?

I'm able to compile the docs on my local machine, I'll share them here so you can use that while we try and figure out what's going on.
[kerchunk_docs.zip](https://github.com/fsspec/kerchunk/files/8672160/kerchunk_docs.zip)


@martindurant seeing as this may be a github issue, is there a way to get someone from github to look at this?

**Comment by keewis** [comment]
Not sure if that's the best way, but there's a contact form [here](https://support.github.com/contact?tags=rr-pages%2Ccat_pages), as far as I can tell that's for github pages.

Did you try rerunning the "Docs" CI after deleting the latest commit in `gh-pages`, though?

**Comment by martindurant** [comment]
@ZPascal , any chance that you can diagnose what's going on here?

**Comment by ZPascal** [comment]
Hi @martindurant and @lsterzinger, you think the problem is related to the push action change, right? Can we use another version of the action as a test? When was the last successful run (timestamp)?

**Comment by lsterzinger** [comment]
@ZPascal The action that's failing is `pages-build-deployment` which seems to be added when you turn on github pages, since it's not related to any of the github action yaml files in `.github/`.

The last successful run was on May 4th, but this was around the time that it was reported that the docs site was down so this may have been the run that brought it down? All future manually-triggered runs on the same commit have failed https://github.com/fsspec/kerchunk/actions/runs/2272091237/attempts/1

**Comment by valeriupredoi** [comment]
hey guys, here's an [example](https://github.com/valeriupredoi/valeriupredoi.github.io/runs/5723246197?check_suite_focus=true) that I had seen frequently (say, once or twice a week) last month. Usually when GH would announce a degraded status on their GH status page - definitely a GH issue and not related to your pages (it would be worth checking the Ruby version in your build though, but that's something else). At any rate, you can unstuck the container by prompting to load again - that's done via a commit to the pages that prompts the rebuild and redeployment, I still see your last such action was 7 days ago, most probably during GH downtime. Try that, bet it'll work :grin:

**Comment by lsterzinger** [comment]
I pushed a change to the docs on `main`, which triggered the sphinx docs build action (https://github.com/fsspec/kerchunk/actions/runs/2309718530) which terminated successfully.

However, the `pages-build-deployment` (the action that has been failing) has not triggered and I don't know if it's possible to trigger it on the latest commit manually (https://github.com/fsspec/kerchunk/actions/runs/2272091237)

**Comment by valeriupredoi** [comment]
hey guys, a few points from me:

- while the full GH Pages site for docs shows a 404 due to crappy GH Pages deployment, you can still access the full docs (the actual site) via shortcutting, mabe put this into your README for when it fails to deploy again:

https://htmlpreview.github.io/?https://github.com/fsspec/kerchunk/blob/gh-pages/index.html

- your actions/checkout module is pretty old, maybe switch to `actions/checkout@v2` 
- an empty commit and push will do the trick to trigger the build and deploy
```
git commit --allow-empty -m "Trigger rebuild"
git push
```
but has to be done where the GH pages live (where the html stuff is) ie in your `gh-pages` branch - which it did via your action that builds the docs and commits to the `gh-pages` branch, so...
- you'd expect that @lsterzinger 's commit from 14 hours ago to have triggered the build - and indeed it did https://github.com/fsspec/kerchunk/runs/6395964545?check_suite_focus=true - look not at the time stamp of the action in the table of actions but at the deploy action that failed - at the top it says `failed 14 hours ago in 4s` - good! Well, not good, but at least you see the thing got triggered
- now, that depends on the report build status action which seems to have passed but if you look at Report Build Status it actually failed to report telemetry https://github.com/fsspec/kerchunk/runs/6395964678?check_suite_focus=true
- in all honesty I've got no clue what that means, but maybe there's actually something wrong with your build? Mine is passing nicely https://github.com/valeriupredoi/valeriupredoi.github.io/runs/6275775209?check_suite_focus=true
- you can just forget about all this GH deployment nonesense (frankly I don't know why they have instated this action - it's full of issues - it's a recent addition and it should have been introduced only after they've tested it thoroughly) and create your own Jekyll build action, see eg https://github.com/valeriupredoi/valeriupredoi.github.io/blob/master/.github/workflows/build-check-site.yml

Hope this helps :beer:

**Comment by valeriupredoi** [comment]
> @valeriupredoi I tried re-running the job and still the same error. When you run into this same issue, there's nothing to be done except just wait? Does it usually take this long?
> 
> I'm able to compile the docs on my local machine, I'll share them here so you can use that while we try and figure out what's going on. [kerchunk_docs.zip](https://github.com/fsspec/kerchunk/files/8672160/kerchunk_docs.zip)
> 
> @martindurant seeing as this may be a github issue, is there a way to get someone from github to look at this?

just noticed this comment, cheers muchly @lsterzinger :beer:

**Comment by martindurant** [comment]
https://fsspec.github.io/kerchunk/ is back. I don't know if the empty PR with updated checkout and empty PR or manually pushing to the gh repo...

**Comment by martindurant** [comment]
Also, sorry for my absence here, been sick and then with a sick child.

**Comment by lsterzinger** [comment]
Awesome, thanks @martindurant! I guess I should have tried a PR as well, I just pushed a docs update directly to `main` which didn't trigger a publish action

**Comment by lsterzinger** [comment]
I fixed that failing build by removing an unnecessary `make html` in the doc build action (unnecessary because the build occurs during the `ammaraskar/sphinx-action@master` call). Now docs build and publish as expected.

**Comment by lsterzinger** [comment]
Thank you for all your help everyone!

**Comment by valeriupredoi** [comment]
awesome, well done, guys! :beer:
