### ISSUE TITLE
netcdf_recording_file NotImplementedError

### ISSUE THREAD

**Issue by rabernat** [fsspec/kerchunk#187]
I tried `netcdf_recording_file` and immediately hit

https://github.com/fsspec/kerchunk/blob/a5e2e33dbcd2d919d726b6a7b03990394572e269/kerchunk/netCDF3.py#L57-L61

I am confused by this code. This code path immediately raises a NotImplementedError, but following that there is a bunch more code. What is going on? Is the NotImplementedError deliberate?

**Comment by martindurant** [comment]
I'm afraid this is on the TODO part. So far, we only handle regular arrays, not record arrays (append dimensions). The code below that line is copied from the original scipy implementation. Completing this shouldn't be hard, but we would (as the comment implies) need to give options for the user on what chunking they would prefer, since in this case - unlike HDF5 - we have choices.
