### ISSUE TITLE
Unexpected time result with MultiZarrToZarr with differing time units

### ISSUE THREAD

**Issue by mccannjb** [fsspec/kerchunk#282]
I have a collection of reference files based on annual NetCDF files (1950-2014). The format of the source files is the same, except at two points in the series where the units of the time dimension shifts.
| Date Start | Date End | `time` Units |
|------------|-----------|--------------|
| 1950-01-01 | 1974-12-31 | `days since 1950-01-01`
| 1975-01-01 | 1999-12-31 | `days since 1975-01-01`
| 2000-01-01 | 2014-12-31 | `days since 2000-01-01`

Loading these files individually, or in groups within those specific time periods (e.g., 1950-1974, 1975-1999, 2000-2014) using `MultiZarrToZarr` works as expected with the proper time dimension. However, if any grouping crosses one or both of these points where the time dimension units change, the resulting time dimension is the full length of the preceding period. For example, creating a reference file using `MultiZarrToZarr` on the set of annual reference files for just the two years 1999 and 2000 results in a time dimension that spans from 1975-1999.

Is this expected behavior? Is there a preprocessing step that I should use before combining these reference files with `MultiZarrToZarr`, or is there a post-processing step I could take after generating the individual year reference files to make sure that the time dimension is consistent across the dataset?

**Comment by martindurant** [comment]
You need to tell kerchunk to attempt to use CF conventions to decode the time values. You would do this by giving `coo_map{"time", "cf:time"}`, ie., produce output coordinate "time" by using CF conventions to interpret the input coordinate also called "time". 
Additionally, you may wish to specify the output data type like `coo_dtypes={"time": "datetime64[s]", ...}` or similar; otherwise, CF will be used again to re-encode the values to a common epoch.
