### ISSUE TITLE
Kerchunk tutorial for July ESIP Meeting

### ISSUE THREAD

**Issue by maxrjones** [fsspec/kerchunk#330]
@norlandrhagen and I both plan to attend the July ESIP meeting and were wondering if there are any plans for a Kerchunk tutorial? We'd be excited to either contribute or lead a tutorial that extends some of the past NetCDF and GRIB examples for Raphael's recent work on GeoTIFFs. cc @martindurant @abarciauskas-bgse @rsignell-usgs for potential interest in such a tutorial

**Comment by abarciauskas-bgse** [comment]
This is great @maxrjones !!! Right now I am planning to repeat the structure of previous Cloud Computing Cluster sessions with 90 minutes of talks and 90 minutes of tutorials. This time around I am thinking all the tutorial leads give a preview of their tutorial during the talks portion so that attendees can be prepared for what is coming.

Questions:
* Would you want to introduce it during the talks portion?
* Do you think 90 minutes is a good length for this tutorial? 
* What type of preparation will attendees need to get the most out of the tutorial?
* Are you all set to lead the session with @norlandrhagen or would you like additional tutorial support?

**Comment by martindurant** [comment]
I would be happy to help produce material and be in virtual attendance, but not there in person. 

> What type of preparation will attendees need to get the most out of the tutorial?

Personally, I think the very best we could hope for, is if the attendees bring some examples of datasets that might be interesting to kerchunk, so that we can turn it into a mini-sprint and have some reference. sets to show for it by the end. That might be asking for a lot, depending on how much familiarity they will have coming in.

**Comment by maxrjones** [comment]
> Would you want to introduce it during the talks portion?

Yes, a lightning intro sounds great!

> Do you think 90 minutes is a good length for this tutorial?

90 minutes for a hands-on walk-through style tutorial is a good length. Based on timelines at recent sprints on other projects, I doubt 90 or 150 minutes would be enough time for people to get set up and make a bunch of progress on their own datasets. I also expect that we'd need more than one leader in person to help participants work on individual examples (Raphael may also be attending remotely) so I would lean towards predefined examples along with instructions on how people can get help with their own datasets after the tutorial.

> What type of preparation will attendees need to get the most out of the tutorial?
> Should we plan to offer use of the ESIP QHub instance to attendees? cc @rsignell-usgs

I think having participants follow along using the ESIP QHub could work great! This would both simplify environment setup and help the examples run in reasonable time, since the example data will be hosted on S3. IMO people are more engaged when actively following along,  but if that's not an option we could do a demo rather than walk-through.

> Are you all set to lead the session with @norlandrhagen or would you like additional tutorial support?

Really excited that @martindurant is happy to help produce material! I think the three of us should be set with me acting as the in-person representative.

**Comment by rsignell-usgs** [comment]
@maxrjones, to support upcoming workshop/tutorials, we have created a nebari deployment (formerly qhub) for ESIP training at https://nebari-workshop.esipfed.org (and running on AWS in region us-west-2). 

We used password authentication instead of github for this deployment, so all we need to onboard a bunch of people quickly is a CSV file list of participants (first_name, last_name, email).   

ESIP has also been given 5TB of object storage on the Open Storage Network to use for training, so we can give workshop participants a chance to write to object storage without incurring any egress charges.

**Comment by abarciauskas-bgse** [comment]
@maxrjones I have just updated the [session page](https://2023julyesipmeeting.sched.com/event/bff6a91038730ebf3e90978f2d7a79a3) to be more clear but sometimes it takes a few minute for the update to register to the live version.

But the sessions will be run concurrently, so I was expecting each tutorial to be 90 minutes. Do you think that is a good length?

In theory we could race through material for both, in sequence, and it would be more like an overview of the tutorials than a deep dive. And then the deep dives could take place in the working session (Cloud Native GeoJam) on Thursday.

**Comment by maxrjones** [comment]
Thanks for sharing the updated session page @abarciauskas-bgse. No concerns about the 90 minute length. Will there be separate rooms/presentation setups for the two tutorials? Also what's the structure for involving remote participants?

**Comment by maxrjones** [comment]
@rsignell-usgs could you please add @norlandrhagen and I to https://nebari-workshop.esipfed.org/ so that we can test the tutorial contents on the Hub? Here's the required info in a csv file.
[kerchunk_instructors.csv](https://github.com/fsspec/kerchunk/files/12016545/kerchunk_instructors.csv)

**Comment by abarciauskas-bgse** [comment]
@maxrjones we only have one room with presentation setup. This was an oversight on my coordination with organizers. I will gladly let the kerchunk tutorial take the official room and those who are interested in the geospatial python workshop, we will try and use the plenary room, but we will not have access to any AV setup. Given the nature of the workshop materials, I think we (those working on the geospatial-python) can make it work.

**Comment by maxrjones** [comment]
> @maxrjones we only have one room with presentation setup. This was an oversight on my coordination with organizers. I will gladly let the kerchunk tutorial take the official room and those who are interested in the geospatial python workshop, we will try and use the plenary room, but we will not have access to any AV setup. Given the nature of the workshop materials, I think we (those working on the geospatial-python) can make it work.

No worries! If it's too much of a hassle to try to use the plenary room without AV setup, we could go with your earlier idea to run through the material in sequence and use the GeoJam on Thursday for deep dives. Really glad to support whatever you prefer for the format, just want to make sure our plans for material are appropriate.

**Comment by abarciauskas-bgse** [comment]
@maxrjones I have updated the session page based on what was decided: https://2023julyesipmeeting.sched.com/event/bff6a91038730ebf3e90978f2d7a79a3 let me know if that looks ok to you. cc @PowerChell @emmalu @torimcd

**Comment by rsignell-usgs** [comment]
@maxrjones I'm here at SciPy with @amsnyder. I'll confab with her today (she was admin the last workshop) and get you set up.     They also used Nebari for the tutorials here at SciPy and they had an automatic registration procedure that was pretty slick.   I'll check with @dharhas who is also here about whether we might use the same approach to onboard users for your tutorial.

**Comment by maxrjones** [comment]
The materials used for this tutorial are all available in the [kerchunk-cookbook](https://projectpythia.org/kerchunk-cookbook/README.html)
