### ISSUE TITLE
MultiZarrToZarr for non-spatial HDF5 files

### ISSUE THREAD

**Issue by dnelson86** [fsspec/kerchunk#333]
My dataset is a bit different than the usual use case, I believe. It is a number of HDF5 files structured as e.g.

```
snap_099.0.hdf5
snap_099.1.hdf5
snap_099.2.hdf5
```

where

```
$ h5ls -r snap_099.0.hdf5
/PartType0               Group
/PartType0/Coordinates   Dataset {1728468, 3}
/PartType0/Density       Dataset {1728468}

$ h5ls -r snap_099.1.hdf5
/PartType0               Group
/PartType0/Coordinates   Dataset {1670262, 3}
/PartType0/Density       Dataset {1670262}

$ h5ls -r snap_099.2.hdf5
/PartType0               Group
/PartType0/Coordinates   Dataset {1671632, 3}
/PartType0/Density       Dataset {1671632}
```

In this example the three files are simply splitting up the two large datasets for convenience. The complete datasets would have shapes and are loadable as:

```
Coordinates = np.zeros((5070362,3), dtype='float64')
Density = np.zeros(5070362, dtype='float32')

offset = 0
for i in range(3):
    with h5py.File('snap_099.%d.hdf5' % i, 'r') as f:
        len = f['PartType0/Coordinates'].shape[0]
        Coordinates[offset:offset+len] = f['PartType0/Coordinates'][()]
        Density[offset:offset+len] = f['PartType0/Density'][()]
    offset += len

Coordinates.shape = [5070362, 3]
Density.shape = [5070362]
```

I have gotten Kerchunk working with a zarr load:

```
h5chunks = SingleHdf5ToZarr('snap_099.0.hdf5', '', inline_threshold=300)
with open('snap_099.0.json','wb') as f:
    f.write(ujson.dumps(h5chunks.translate()).encode())

snapshot = zarr.load(fsspec.filesystem("reference", fo="snap_099.0.hdf5.json").get_mapper(""))
snapshot['PartType0/Density']
Out[9]:
array([2.1692520e-06, 2.0380169e-06, 1.7883651e-06, ..., 3.3942027e-07,
       1.8411392e-07, 4.2490501e-07], dtype=float32)
```

(very cool!)

But I do not see how/if `MultiZarrToZarr` can be applied in this case. Does any of the existing functionality of `coo_map` apply?

**Comment by martindurant** [comment]
In principle,  you can stitch together your datasets into any pattern that makes sense. In this case, that appears to be "axis 0". However, this is not a netCDF-style layout, I think, so kerchunk won't be able to automatically know how to lay out your chunks, and MutiZarrToZarr probably can't do the right thing.

There is an option in `coo_map` to get the concatenation coordinate(s) from an arbitrary function which is passed all the details of the chunk being considered, including filename and the dataset itself so that you can extract values or attributes. Maybe it can be made to work

Alternatively, the references' structure is pretty simple. In the JSON of each file, you will have keys like "/PartType0/Coordinates/i.0", and the three of these from the three datasets would map to "/PartType0/Coordinates/i.0", "/PartType0/Coordinates/(x+i).0", "/PartType0/Coordinates/(x+y+i).0" where x is the number of chunks in the first dataset and y is the number of chunks in the second. You would also need to update the .zarray to the total shape of the final output.

All of this assumes that the chunks in the three datasets are compatible: all the same shape and (first the first two files) complete. Unfortunately, zarr is not able to loosen this restriction yet ( https://github.com/zarr-developers/zeps/blob/main/draft/ZEP0003.md ).

**Comment by dnelson86** [comment]
Yes "axis 0 stacking" is essentially what I am after.

Just to clarify your large two paragraphs: when you say 'dataset' do you mean 'file' (of which there are 3 in my example) or 'dataset' (of which there are 2: Coordinates and Density)?

Does the structure above satisfy the requirements you describe? In my case, in a given file, every dataset has exactly the same axis 0 size. But this size differs from file to file.

I would be happy if, on the zarr side, there were "no chunks". But, am I understanding correctly that the whole Kerchunk concept requires that a dataset from each original HDF5 file be represented as exactly one chunk of a zarr dataset? (Thus my use case would need to wait for ZEP3?)

**Comment by martindurant** [comment]
> that the whole Kerchunk concept requires that a dataset from each original HDF5 file be represented as exactly one chunk of a zarr dataset?

No, in most cases and certainly for HDF, each native chunk of the original data becomes one chunk in the zarr virtual dataset. It is this internal chunk size that matters. Zarr will be able to tell you what this chunking is for each of the kerchunked reference sets.

**Comment by dnelson86** [comment]
In my case, all the original HDF5 datasets are always unchunked.

**Comment by martindurant** [comment]
Oh OK - so that says you have chunks that are the same size as the whole array, and so mismatched between the files. Indeed, we cannot combine these without ZEP003.

**Comment by dnelson86** [comment]
Yes I see, many thanks for the clarifications! We will be looking forward to this in the future for sure.
